### ISSUE TITLE
"Coverage error" in chrome

### ISSUE THREAD

**Issue by Jc2k** [codecov/browser-extension#28]
Chrome Version 50.0.2661.94 (64-bit)

This is for a python project, we are using the latest version of the codecov (2.0.3) package if that matters. It's on a private repo on the PR view.

From the console view:

```
TypeError: Cannot read property 'ignored' of undefined
    at HTMLDivElement.<anonymous> (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:460:31)
    at Function.n.extend.each (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:2882)
    at n.fn.n.each (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:847)
    at Github.window.Github.Github.overlay (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:413:38)
    at Github.window.Codecov.Codecov._process (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:230:19)
    at Object.$.ajax.success (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:184:21)
    at j (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:26911)
    at Object.k.fireWith [as resolveWith] (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:27724)
    at x (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:4:11065)
    at XMLHttpRequest.<anonymous> (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:4:14577)
```

It seems to be working for non-pr stuff.

**Comment by htmldoug** [comment]
I'm seeing this too. Failing on a file, `fp`, that isn't present in `report.files[fp]`. `file_data` gets set to undefined and we blow up on `else if (file_data.ignored === true) `.

Here's a screenshot where I'm failing:
![screen shot 2016-05-10 at 10 45 22 pm](https://cloud.githubusercontent.com/assets/663139/15168664/66fb14e8-1701-11e6-956a-5df36af315a7.png)

**Comment by stevepeak** [comment]
Closed via https://github.com/codecov/browser-extension/commit/b034a737553af90d9e7dba00e39ddec585ff6d02
