### ISSUE TITLE
"Coverage Error" in Chrome / OSX

### ISSUE THREAD

**Issue by joaofraga** [codecov/browser-extension#31]
I'm having the following error when using Codecov extension on the PR view:

"Coverage Error"

On console I get:

```
TypeError: Cannot read property 'c' of undefined
    at Github.window.Github.Github.overlay (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:388:28)
    at Github.window.Codecov.Codecov._process (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:230:19)
    at Object.success (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:184:21)
    at j (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:26911)
    at Object.fireWith [as resolveWith] (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:27724)
    at x (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:4:11065)
    at XMLHttpRequest.<anonymous> (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:4:14577)
```

**Chrome** 51.0.2704.63 (64-bit)
**Codecov** 1.0.4

**Comment by maxkostow** [comment]
Looks like it might be an API issue. In the response parsed here: https://github.com/codecov/browser-extension/blob/master/lib/codecov.js#L320 the `res.report` is a string like `"<Report files=3102>"`

**Comment by stevepeak** [comment]
Fixed up! Thank you for pointing these issues out.

**Comment by joaofraga** [comment]
Thank you @stevepeak!
