### ISSUE TITLE
CodeCov breaking on most recent github

### ISSUE THREAD

**Issue by kenzierocks** [codecov/browser-extension#37]
I was viewing https://github.com/sciactive/pnotify/blob/master/src/pnotify.animate.js and kept getting this error in console:
```
Error in response to storage.get: TypeError: Cannot read property 'split' of undefined
    at Github.window.Github.Github.get_ref (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:370:49)
    at Github.window.Codecov.Codecov._start (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:123:21)
    at Github.Codecov (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:101:10)
    at new Github (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:349:41)
    at window.create_codecov_instance (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:333:12)
    at null.callback (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:27:24)
    at HTMLDocument.<anonymous> (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/codecov.js:9:23)
    at j (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:26911)
    at Object.fireWith [as resolveWith] (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:27724)
    at Function.ready (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:29518)
    at I (chrome-extension://keefkhehidemnokodkdkejapdgfjmijf/lib/jquery-2.1.3.min.js:2:29709)
```

**Comment by stevepeak** [comment]
Thanks for pointing this out. I'll investigate the storage cache.

I'm actually seeing no coverage data at https://codecov.io/gh/sciactive/pnotify

**Comment by stevepeak** [comment]
@kenzierocks I'm unable to replicate this :( Are you still experiencing this issue?

**Comment by kenzierocks** [comment]
Yes I am. I'm going to try removing other extensions that might be causing the problem.

**Comment by kenzierocks** [comment]
With no other extensions but CodeCov, I get this error instead:
```
GET https://codecov.io/api/gh/dcherman/jquery.pagevisibility/commits/1cec38d747a950cf5e7dabb4c576f6e24b8f4a6d?src=extension 404 (Not Found)
send @ jquery-2.1.3.min.js:4
ajax @ jquery-2.1.3.min.js:4
window.Codecov.Codecov._get @ codecov.js:176
(anonymous function) @ codecov.js:155
(anonymous function) @ codecov.js:3
target.(anonymous function) @ extensions::SafeBuiltins:19
safeCallbackApply @ extensions::sendRequest:21
handleResponse @ extensions::sendRequest:74
```

**Comment by kenzierocks** [comment]
It looks like one of my extensions was interfering with all pages ending in `.js`. It'd still be nice for the 404 to not be shown in console.

**Comment by stevepeak** [comment]
The only way to "hide" 404's in the console would be for codecov to return 200's and have the extension understand it was actually a 404.

Is there a more specific reason for "nice for the 404 to not be shown in console"?

**Comment by kenzierocks** [comment]
No, didn't realize it was not possible. I just like keeping my console error free if possible.
